---
title: "RHEAS yield prediction visualization"
author: "Benson Kenduiywo"
date: "08/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data

Load data

```{r d1}
#df <- read.csv('D:/RCMRD/Code/Rheas_Yields/kenya_1990_2022.csv')
#head(df,n =5)
df <- read.csv('D:/RCMRD/Code/Rheas_Yields/uganda_1990_2022.csv')
```


## Data preparation

Extract Harvest & plant dates into months and years

```{r d2}
df$harvest <- as.Date(df$harvest)
df$planting <- as.Date(df$planting)
df$h_month  <- as.numeric(format(df$harvest,"%m"))
df$h_year  <- as.numeric(format(df$harvest,"%Y"))
df$p_month  <- as.numeric(format(df$planting,"%m"))
df$p_year  <- as.numeric(format(df$planting,"%Y"))
head(df, 5)
```

Let's define/extract the various seasons in Kenya.

```{r s1}
#Long Rain Long Dry (LRLD) season
#df$season <- df[df$p_month > 1 & df$p_month < 6, ]
df$season <- NA
df$season[df$p_month > 1 & df$p_month < 6] <- 'LRLD'
#Short Rain Short Dry (SRSD)
df$season[df$p_month > 9 & df$p_month <= 12] <- 'SRSD'
#sd <- df[df$p_month > 9 & df$p_month <= 12,]

```


lets now aggregate RHEAS estimated yields per year per county.

```{r y1}
#lr <- aggregate(df[,'gwad'], df[ , c("cname", "h_year")], mean, na.rm=TRUE)
yields <- aggregate(gwad~cname+h_year, df, mean, na.rm=TRUE)
#names(yields)[1] <- 'district'
write.csv(yields, 'D:/RCMRD/Code/Rheas_Yields/uganda_aggregated_1990_2022.csv')

```


## Plots

```{r y1}
plot(gwad~h_year, data=yields, type='l')
x11()
boxplot(gwad~h_year, data=yields, xlab='Year', ylab = 'Maize yields (kg/ha)')
```

